# -*- coding: utf-8 -*-
"""파이선 기본 시각화.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RIeAyVYr1h4_-NM2SAZoPP6Mxo6kQn9l
"""

import pandas as pd

import matplotlib.pyplot as plt
import numpy as np

# %matplotlib inline

plt.figure() # 박스 그려주는 친구 . 그래프 그릴댄 이 3개가 기본
plt.plot([1,2,3,4,5,6,7,8,9,8,7,6,5,4,3,2,1])
plt.show

t = np.arange(0,12, 0.01) #0부터 12까지 0.01 간격으로

y = np.sin(t)
z = np.cos(t)

plt.figure(figsize=(10,6))
plt.plot(t, y ,label = 'sin', lw = 5) # lw = 굵기
plt.plot(t, z, 'r--', label = 'cos', color = 'red' , linestyle = 'dashed', marker = 'o')  # g^는 산모양 , r^ 는 빨간색 산, r--는 점선
plt.legend()
plt.grid()
plt.xlabel('time')
plt.ylabel('value')
plt.title('mygraph')
plt.show()

t2 = np.arange(0, 5, 0.5)

plt.figure(figsize = (10,6))
plt.plot(t2, t2 , 'r--')
plt.plot(t2 , t2*2 , 'bs')
plt.plot(t2 , t2*3 , 'g^')
plt.plot(t2 , t2*4, color='pink', linestyle = 'dashed' , marker ='o')
plt.legend()
plt.grid()
plt.xlabel('time')
plt.ylabel('value')
plt.title('mygraph')
plt.show()

s1 = np.random.normal(loc=0 , scale = 1 , size = 1000) # 평균 0,  1000까지 편차가 1인 숫자 생성
s2 = np.random.normal(loc=5, scale = 0.5 , size = 1000)
s3 = np.random.normal(loc=10 , scale = 2 , size = 1000)

plt.figure(figsize = (10,6))
plt.plot(s1, label ='s1')
plt.plot(s2, label = 's2')
plt.plot(s3 , label = 's3')
plt.legend()
plt.show()

plt.figure(figsize = (10,6))
plt.boxplot((s1, s2, s3,)) # 상하한값 
plt.show()

